openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /message:
    get:
      summary: Get Messages
      tags:
        - Messages
      description: Retrieves a list of messages.
      parameters:
        - name: status
          in: query
          description: Filter messages by status
          required: false
          schema:
            type: "string"
            enum:
              - "sent"
              - "read"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  messages:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        uuid: 
                          type: "string"
                        text:
                          type: "string"
                        status:
                          type: "string"
                          enum:
                            - "sent"
                            - "read"
              example:
                messages:
                  - text: "Test message 1"
                    status: "read"
                  - text: "Test message 2"
                    status: "sent"
                  - text: "Test message 3"
                    status: "sent"
  /message/send:
    post:
      summary: Send a Message
      tags:
        - Messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
            example:
              text: "Hi there!"
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Message sent"
        '400':
          description: Validation error
