controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

openapi_spec:
    path: /openapi.yaml
    controller: App\Controller\OpenApiController::serveSpec

